version: "3"
services:
  oracle-simple-dev:
    stdin_open: true
    tty: true
    image: registry.gitlab.com/heb-engineering/teams/enterprise/sco/spur/supplier-buildpack/oracle:c6b2594fe2a2e47477c252189dff3c4df7b3c7d4
    working_dir: $PROJECT_DIR
    volumes:
      #Mount application code
      - .:/$PROJECT_DIR
      #Mount docker socket so that docker can be used on image
      - $DOCKER_SOCKET_PATH:/var/run/docker.sock
      - stack:/root/.stack
      - stack-work:/$PROJECT_DIR/.stack-work

  gke-tools:
    stdin_open: true
    tty: true
    image: registry.gitlab.com/heb-engineering/teams/enterprise/sco/spur/supplier-buildpack/spur-gke-tools/helm3:be04d1ce06dc6b655c18e9b2dbbcc3227e440101
    working_dir: $PROJECT_DIR
    volumes:
      #Mount application code
      - .:/$PROJECT_DIR
      #Mount docker socket so that docker can be used on image
      - $DOCKER_SOCKET_PATH:/var/run/docker.sock
      - stack:/root/.stack
      - stack-work:/$PROJECT_DIR/.stack-work

volumes:
  stack:
    name: stack
    external: true
  stack-work:
