CREATE USER emd IDENTIFIED by "test" QUOTA UNLIMITED ON USERS CONTAINER=ALL;
GRANT ALL PRIVILEGES TO emd CONTAINER=ALL;
GRANT CONNECT, RESOURCE TO emd CONTAINER=ALL;
GRANT CREATE SESSION to emd CONTAINER=ALL;
GRANT CREATE ANY TABLE to emd CONTAINER=ALL;
GRANT UNLIMITED TABLESPACE TO emd CONTAINER=ALL;
GRANT CHANGE NOTIFICATION TO emd CONTAINER=ALL;
